inputs:
  TEAM_SLUG:
    description: 'Name of org team defining members to be pinged'
  REPO_NAME:
    description: 'Name of repo to be mentioned in failure message'
  ISSUE_NUM:
    description: 'Issue number in which message is to be posted'

name: 'Ping Dev Team'
description: 'Ping the rOpenSci dev-guide team on workflow failures'
runs:
  using: "composite"
  steps:
    - name: Get Dev Team Members
      shell: bash
      run: |
          curl -Ls \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/orgs/ropensci/teams/${{inputs.TEAM_SLUG}}/members |
              jq -r '[.[] | .login] | join(",@")' | awk '{print "@" $0}' > team.txt

    - name: Message
      shell: bash
      run: |
          TEAM=$(cat team.txt)
          MSG="${TEAM} The ${REPO_NAME} workflow has failed."

    - name: Comment
      shell: bash
      run: gh issue comment $ISSUE_NUM -b "$MSG"
