name: 'Ping Dev Team'
description: 'Ping the rOpenSci dev-guide team on workflow failures'
runs:
  using: "composite"
  env:
    ORG: ropensci
    GITHUB_TOKEN: ${{ secrets.MY_GH_TOKEN }}
  steps:
    - name: Get Dev Team Members
      description: 'Extract members of ropensci/dev-guide and prepend @ to each'
      shell: bash
      run: |
          curl -Ls \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/orgs/$ORG/teams/$TEAM_SLUG/members |
              jq -r '[.[] | .login] | join(",@")' | awk '{print "@" $0}' > team.txt

    - name: Message
      description: 'Construct the message to be posted'
      shell: bash
      run: |
          TEAM=$(cat team.txt)
          MSG="${TEAM} The ${REPO_NAME} workflow has failed."

    - name: Comment
      shell: bash
      run: gh issue comment $ISSUE_NUM -b "$MSG"
