inputs:
  TEAM_SLUG:
    description: 'Name of org team defining members to be pinged'
  REPO_NAME:
    description: 'Name of repo to be mentioned in failure message'
  ISSUE_NUM:
    description: 'Issue number in which message is to be posted'

name: 'Ping Dev Team'
description: 'Ping the rOpenSci dev-guide team on workflow failures'
runs:
  using: "composite"
  steps:
    - name: Message
      shell: bash
      id: message_step
      run: |
          MSG="${TEAM} The ${REPO_NAME} workflow has failed."
          echo "$MSG"
          echo "::set-output name=MSG::$MSG"
      env:
        TEAM: '@maelle @mpadge'

    - name: Comment
      shell: bash
      run: |
        echo "gh issue comment $ISSUE_NUM -b ${{ steps.message_step.outputs.MSG }}"
        gh issue comment "$ISSUE_NUM" -b "${{ steps.message_step.outputs.MSG }}"
