inputs:
  TEAM_SLUG:
    description: 'Name of org team defining members to be pinged'
  REPO_NAME:
    description: 'Name of repo to be mentioned in failure message'
  ISSUE_NUM:
    description: 'Issue number in which message is to be posted'

name: 'Ping Dev Team'
description: 'Ping the rOpenSci dev-guide team on workflow failures'
runs:
  using: "composite"
  steps:
    - name: Message
      shell: bash
      run: |
          MSG="${TEAM} The ${REPO_NAME} workflow has failed."
      env:
        TEAM: '@maelle @mpadge'

    - name: Comment
      shell: bash
      run: gh issue comment $ISSUE_NUM -b "$MSG"
