inputs:
  REPO_NAME:
    description: 'Name of repo to be mentioned in failure message'
  ISSUE_NUM:
    description: 'Issue number in which message is to be posted'
  TOKEN:
    description: 'GitHub token required for cli actions'

name: 'Ping Dev Team'
description: 'Ping the rOpenSci dev-guide team on workflow failures'
runs:
  using: "composite"
  steps:
    - name: Get Dev Team Members
      shell: bash
      run: |
        curl -Ls \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GH_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/orgs/ropensci/teams/dev-guide/members > team.json
      env:
        GH_TOKEN: ${{ inputs.TOKEN }}

    - name: Dump json
      shell: bash
      run: |
        jq . team.json

    - name: Message
      shell: bash
      id: message_step
      run: |
        MSG="${TEAM} The ${{ inputs.REPO_NAME }} workflow has failed."
        echo "$MSG"
        echo "MSG=${MSG}" >> $GITHUB_ENV
      env:
        TEAM: '@maelle @mpadge'

    - name: Comment
      shell: bash
      run: |
        echo 'gh issue comment ${{ inputs.ISSUE_NUM }} -b "${MSG}"'
        gh issue comment "${{ inputs.ISSUE_NUM }}" -b "${MSG}"
      env:
        GH_TOKEN: ${{ inputs.TOKEN }}
