inputs:
  REPO_NAME:
    description: 'Name of repo to be mentioned in failure message'
  ISSUE_NUM:
    description: 'Issue number in which message is to be posted'
  TOKEN:
    description: 'GitHub token required for cli actions'

name: 'Ping Dev Team'
description: 'Ping the rOpenSci dev-guide team on workflow failures'
runs:
  using: "composite"
  steps:
    - name: Message
      shell: bash
      id: message_step
      run: |
        WFURL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        MSG="${TEAM} The ${{ inputs.REPO_NAME }} workflow has failed at $WFURL."
        echo "$MSG"
        echo "MSG=${MSG}" >> $GITHUB_ENV
      env:
        TEAM: '@maelle @mpadge'

    - name: Comment
      shell: bash
      run: |
        echo 'gh issue comment ${{ inputs.ISSUE_NUM }} -b "${MSG}"'
        gh issue comment "${{ inputs.ISSUE_NUM }}" -b "${MSG}"
      env:
        GH_TOKEN: ${{ inputs.TOKEN }}
